name: "Build manufacturing files"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - "**"
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - 'footprints.pretty/*'
      - 'footprints_project_specific.pretty/*'
      - 'libraries/*'
      - '.github/workflows/ci.yml'
      - 'config.kibot.yaml'
      - 'bom.ini'
    # Ignore the push event when creating tags
    tags-ignore:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
  release:
    types:
      - published

jobs:
  create_manufacturing_files:
    permissions:
      contents: write
    strategy:
      matrix:
        project:
          - name: UV LED
            schematic: reference_board.kicad_sch
            pcb: reference_board.kicad_pcb
            config: config.kibot.yaml
            variants: "[ 'default', 'PCBA' ]"
    uses: ./.github/workflows/build-kicad.yml
    with:
      schematic: ${{ matrix.project.schematic }}
      pcb: ${{ matrix.project.pcb }}
      config: ${{ matrix.project.config }}
      name: ${{ matrix.project.name }}
      variants: ${{ matrix.project.variants }}
